package com.mains.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "Jobs_table")
public class Job {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;
    
    //Id is autogenerated. this allows the id to autoiterate when a new job is added.
    
    // declares vars outside of id 

    private String name;
    private String description;
    private String status;
    private int hours;
    
    //getters and setters for everything
    
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getId() {
		return id;
	}

	public int getHours() {
		return hours;
	}

	public int setHours(int hours) {
		return this.hours = hours;
	}

}